core/urls.py
from django.conf.urls import url
from core import views
from core.services import Scheduler
from django.urls import path


app_name = 'core'

urlpatterns = [
    path('home_global.css/', views.StyleSettingsView.as_view(), name='home-global'),
    path('test-quill/<int:pk>/', views.TestViewQuill.as_view(), name='test_view'),
    path('test-tiny/<int:pk>/', views.TestViewTiny.as_view(), name='test_view'),
]

correspondence/urls.py
from django.conf.urls import url
from correspondence import views
from django.urls import path

import correspondence.api_views

app_name = 'correspondence'

urlpatterns = [
    path('api/v1/radicates/', correspondence.api_views.RadicateList.as_view(), name='search_radicates'),
    path('api/v1/radicates/<str:radi_number>/', correspondence.api_views.RadicateDetail.as_view(), name='search_radicate'),
    path('api/v1/radicates/file/<str:radi_number>/', correspondence.api_views.FileDetail.as_view(), name='search_radicate_file'),
    url(r'^$', views.index, name='index'),
    path('search-names/', views.search_names, name='search_names'),
    path('users-by-area/', views.users_by_area, name='users_by_area'),
    path('return-to-last-user/<int:radicate>', views.return_to_last_user, name='return_to_last_user'),
    path('report-to-user/<int:radicate>', views.report_to_user, name='report_to_user'),
    path('delete-from-reported/<int:radicate>', views.delete_from_reported, name='delete_from_reported'),
    path('assign-user/<int:radicate>', views.assign_user, name='assign_user'),
    path('search-content/', views.search_by_content, name='search_by_content'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('radicate/create/<int:person>/', views.create_radicate, name='create_radicate'),
    path('radicate/list/', views.RadicateList.as_view(), name='list_radicate'),
    path('radicate/<int:pk>/', views.RadicateDetailView.as_view(), name="detail_radicate"),
    path('radicate_review/<int:pk>/', views.RadicateDetailReview.as_view(), name="detail_radicate_review"),
    path('radicate-detail/<str:cmis_id>/', views.detail_radicate_cmis, name="detail_radicate_cmis"),
    path('edit-radicate/<int:id>/', views.edit_radicate, name='edit_radicate'),
    path('current-user/<int:pk>/', views.CurrentUserUpdate.as_view(), name='current_user'),
    path('recordassigned/<int:pk>/', views.RecordAssignedUpdate.as_view(), name='recordassigned'),
    path('person/create/', views.PersonCreateView.as_view(), name='create_person'),
    path('update-person/<int:pk>/', views.PersonUpdateViewNew.as_view(), name='update_person'),
    path('create-person-attorny/<uuid:pqrs_type>/', views.PersonAtronyCreate.as_view(), name='create_person_attorny'),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='detail_person'),
    path('edit-person/<int:pk>/', views.PersonUpdateView.as_view(), name='edit_person'),
    path('legal-person/create/', views.LegalPersonCreateView.as_view(), name='create_legal_person'),
    path('legal-person-update/<int:pk>/', views.LegalPersonUpdateView.as_view(), name='update_legal_person'),
    path('register/', views.register, name='register'),
    path('charts/', views.charts, name='charts'),
    path('project-answer/<int:pk>/', views.project_answer, name='project_answer'),
    path('record/create/', views.RecordCreateView.as_view(), name='create_record'),
    path('record-detail/<int:pk>/', views.RecordDetailView.as_view(), name='detail_record'),
    path('record/edit/<int:pk>/', views.RecordUpdateView.as_view(), name='edit_record'),
    path('record/list/', views.RecordListView.as_view(), name='list_records'),
    path('record/process-excel-radicates/', views.ProcessExcelRadicates.as_view(), name='process_excel_radicates'),
    path('search-person/',views.search_user,name="search_person"),
    path('radicate/thumbnail/', views.get_thumbnail, name='get_thumbnail'),
    path('radicate/file/', views.get_file, name='get_file'),
    path('get-alerts/', views.get_alerts, name='get_alerts'),
    path('disable-alert/', views.disable_alert, name='disable_alert'),
    path('create-pqrs/<uuid:pqrs>/',views.create_pqr_type,name='create_pqrs'),
    path('finish-pqrs/<uuid:pqrs>/',views.finish_pqrs,name='finish_pqrs'),
    path('request-internal-info/<int:radicate>/', views.request_internal_info, name='request_internal_info'),
    path('answer-request/<int:pk>/', views.answer_request, name='answer-request'),
]

rino/urls.py
from django.contrib import admin
from django.urls import include,path
from correspondence import views
from pqrs import views as pqrs_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views as core_views
from django.conf.urls import url

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('correspondence/', include('correspondence.urls', namespace='correspondence')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('workflow/', include('workflow.urls', namespace='workflow')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', views.index, name='index'),
    # reset passwords urls
    path('password_reset/', core_views.password_reset_request, name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('calendar/holidays/', core_views.holidays, name='holidays'),
    path('calendar/weekends/', core_views.weekends, name='weekends'),
    path('calendar/not-working-days/', core_views.not_working_days, name='not_working_days'),
    path('signature_flow/users/', core_views.signature_flow_users, name='signature_flow_users'),
    #path('password_reset/', include('password_reset.urls', namespace='password_reset'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # to import static in deployment



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workflow/urls.py
from django.conf.urls import url
from django.urls import path
from workflow import views

app_name = 'workflow'

urlpatterns = [
    path('signature/<int:radicate>', views.signature, name='signature'),
    path('filing/<int:radicate>', views.filing, name='filing')
]

workflow/models.py
from django.db import models
from django.contrib.auth.models import User
from pqrs.models import SubType
from core.models import FunctionalArea
from django.utils.translation import gettext_lazy as _

class SignatureFlow(models.Model):
    name = models.CharField(max_length=128, null=True, blank=True, default='')
    description = models.CharField(max_length=256, null=True, blank=True, default='')

    def __str__(self):
        return self.name

class SignatureAreaUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    area = models.ForeignKey(FunctionalArea, on_delete=models.SET_NULL, null=True, blank=True)
    signature_flow_id = models.IntegerField(null=False, default=1)

class SignatureNode(models.Model):
    class Types(models.TextChoices):
        INPUT = 'Inicio', _('Inicio')
        OUTPUT = 'Fin', _('Fin')
        GUARANTORUSER = 'Visto Bueno', _('Visto Bueno')
        SIGNINGUSER = 'Firma Personal', _('Firma Personal')
        LEGALSIGNINGUSER = 'Firma Jurídica', _('Firma Jurídica')

    index = models.IntegerField(null=False, default=1)
    type = models.CharField(max_length=50)
    previous = models.ManyToManyField("self", symmetrical=False)
    properties = models.CharField(max_length=512)
    signature_flow = models.ForeignKey(SignatureFlow, on_delete=models.CASCADE)
    area_user = models.ForeignKey(SignatureAreaUser, on_delete=models.SET_NULL, null=True, blank=True)
    time = models.IntegerField(null=False, default=2)

    def __str__(self):
        return f'{self.type} {self.previous}'

class FilingFlow(models.Model):
    subtype = models.OneToOneField(SubType, on_delete=models.PROTECT, null=False)

    def __str__(self):
        return f'{self.subtype.name}'

class FilingAreaUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    area = models.ForeignKey(FunctionalArea, on_delete=models.SET_NULL, null=True, blank=True)
    filing_flow_id = models.IntegerField(null=False, default=1)

class FilingNode(models.Model):
    class Types(models.TextChoices):
        INPUT = 'Inicio', _('Inicio')
        OUTPUT = 'Fin', _('Fin')
        ASSIGNEDUSER = 'Asignar', _('Asignar')
        INFORMEDUSER = 'Notificar', _('Notificar')

    index = models.IntegerField(null=False, default=1)
    type = models.CharField(max_length=50)
    previous = models.ManyToManyField("self", symmetrical=False)
    properties = models.CharField(max_length=512)
    filing_flow = models.ForeignKey(FilingFlow, on_delete=models.CASCADE)
    area_users = models.ManyToManyField(FilingAreaUser, symmetrical=False)
    time = models.IntegerField(null=False, default=2)

    def __str__(self):
        return f'{self.type} {self.previous}'

workflow/forms.py
from django import forms
import json
from workflow.models import SignatureFlow, FilingFlow
from workflow.services import FlowService
from workflow.widgets import SignatureFlowWidget, FilingFlowWidget


class SignatureFlowAdminForm(forms.ModelForm):

    id = forms.CharField(max_length=50, required=False, widget=SignatureFlowWidget(), label='Graph')

    def clean(self, *args, **kwargs):

        cleaned_data = super(SignatureFlowAdminForm, self).clean()
        if self.data['id'] != -1:
            if self.data['graph'].strip():
                graph = json.loads(self.data['graph'])
                sf = FlowService.from_json(graph, FlowService.FlowType.SIGNATURE, self.cleaned_data['id'])

        return cleaned_data

    class Meta:
        model = SignatureFlow
        fields = ['name', 'description', 'id']

class FilingFlowAdminForm(forms.ModelForm):

    id = forms.CharField(max_length=50, required=False, widget=FilingFlowWidget(), label='Graph')

    def clean(self, *args, **kwargs):

        cleaned_data = super(FilingFlowAdminForm, self).clean()
        if self.data['id'] != -1:
            if self.data['graph'].strip():
                graph = json.loads(self.data['graph'])
                sf = FlowService.from_json(graph, None, self.cleaned_data['id'])

        return cleaned_data

    class Meta:
        model = FilingFlow
        fields = ['subtype', 'id']

workflow/views.py
from django.shortcuts import render
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.http import HttpResponseRedirect
import json
from workflow.services import FlowService

def signature(request, radicate):

    graph_error = ''
    if request.method == 'POST':
        id = request.POST['id']
        next_view = request.POST['next']
        graph = json.loads(request.POST['graph'])
        try:
            sf = FlowService.from_json(graph, FlowService.FlowType.SIGNATURE, id if id and id != 'None' else None)
            id = sf.id
        except ValidationError as e:
            messages.error(request, e.message)
        except:
            messages.error(request, "Something else went wrong")
        if next_view and next_view != 'None':
            return HttpResponseRedirect(reverse(next_view))

    if request.method == 'GET':
        next_view = request.GET.get('next')
        id = request.GET.get('id')
        graph = FlowService.to_json(id, FlowService.FlowType.SIGNATURE)

    return render(
        request,
        'workflow/signature_flow.html',
        context={
            'id': id,
            'graph': graph,
            'radicate': radicate,
            'grapherror' : graph_error,
            'next': next_view
        })

def filing(request, radicate):

    graph_error = ''
    if request.method == 'POST':
        id = request.POST['id']
        next_view = request.POST['next']
        graph = json.loads(request.POST['graph'])
        try:
            sf = FlowService.from_json(graph, None, id if id and id != 'None' else None)
            id = sf.id
        except ValidationError as e:
            messages.error(request, e.message)
        #except:
        #    messages.error(request, "Something else went wrong")
        if next_view and next_view != 'None':
            return HttpResponseRedirect(reverse(next_view))
            
    if request.method == 'GET':
        next_view = request.GET.get('next')
        id = request.GET.get('id')
        graph = FlowService.to_json(id)

    return render(
        request,
        'workflow/filing_flow.html',
        context={
            'id': id,
            'graph': graph,
            'radicate': radicate,
            'grapherror' : graph_error,
            'next': next_view
        })

templates/workflow/find_user.html
{% load static %}

<div class="row">
  <div class="tree">
    {% for item, info,last_leaf in functional_tree %}
    {% if info.open %}
    {% if info.level != 0 %}
    <div id="cont{{item.parent.id}}" class="collapse">
      {% endif %}
      <ul>
        <li>
          {% else %}
        </li>
        <li>
          {% endif %}
          {% if last_leaf %}
          <span style="color: #000;"><i class="fas fa-warehouse mr-1"></i><label
              {% if target %}
              onclick="searchPeople('{{item.pk}}', `{% url 'correspondence:users_by_area' %}`, '{{item.parent.name}}/{{item.name}}', '3', '#{{target}}')"
              {% else%}
              onclick="searchPeople('{{item.pk}}', `{% url 'correspondence:users_by_area' %}`, '{{item.parent.name}}/{{item.name}}', '3')"
              {% endif %}
              >
              {{ item }}</label></span>
          {% else %}
          <span>
            <a style="color:#000; text-decoration:none;" data-toggle="collapse" href="#cont{{item.pk}}"
              aria-expanded="false" aria-controls="cont{{item.pk}}">
              <i class="collapsed">
                <i class="fas fa-building"></i>
              </i>
              <i class="expanded">
                <i class="far fa-building"></i>
              </i>
              {{ item }}
            </a>
          </span>
          {% endif %}

          {% for close in info.close %}
        </li>
      </ul>
      {% if info.level != 0 and info.open%}
    </div>
    {% endif %}
    {% endfor %}
    {% endfor %}
  </div>
</div>

<h5 class="mt-2 text-primary">Área seleccionada: <span id="headerForm"></span></h5>
<input id="{{target}}_area" name="{{target}}_area" type="hidden" value="">
<div class="col text-center">
  {% if target %}
  <select name="{{target}}" class="selectpicker" id="{{target}}"></select>
  {% else %}
  <select name="user_selected" class="selectpicker" id="user_selected"></select>
  {% endif %}

</div>

templates/workflow/select_user.html
{% load static %}
{% load worflow_tags %}
{% find_user 'user_selected' %}

<div class="col text-center">  
  <input id="user_selected_submit"  class="btn btn-success" value="Asignar"></p>
</div>

templates/workflow/select_user_and_time.html
{% load static %}
{% load worflow_tags %}
{% find_user 'user_selected' %}

<div class="col text-center">
  tiempo máximo (horas): 
  <input id="user_selected_time" type="number" name="tuser_selected_time" min="0" max="100"> 
</div>
<div class="col text-center">  
  <input id="user_selected_submit" class="btn btn-success" value="Asignar"></p>
</div>

templates/workflow/select_users.html
{% load static %}
{% load worflow_tags %}
{% find_user 'users_selected' %}

<div class="container pt-4">
	<div class="table-responsive">
	<table class="table">
		<tbody id="tbody">
		</tbody>
	</table>
	</div>
</div>

<div class="col text-center">  
  <input id="users_selected_submit" class="btn btn-success" value="Asignar"></p>
</div>

templates/workflow/signature_flow.html
{% extends 'correspondence/main_template.html' %}
{% load static %}
{% block content %}

<style type="text/css" scoped>

.inicio {
    background-color: #e9c46a !important;
    border-radius: 50% !important;
    min-width: 80px !important;
    width: 80px !important;
}

.fin {
    background-color: #e9c46a !important;
    border-radius: 50% !important;
    min-width: 80px !important;
    width: 80px !important;
}
.visto-bueno {
    background-color: rgba(177, 191, 250, 1) !important;
    min-width: 140px !important;
    width: 140px !important;
}

.firma-personal {
    background-color: #95d5b2 !important;
    border: 2px solid #658542 !important;
    min-width: 140px !important;
    width: 140px !important;
}

.firma-jurídica {
    background-color: #ed2939 !important;
    border: 2px solid #960018 !important;
    min-width: 140px !important;
    width: 140px !important;
}

.selected {
    border-color: #e3c000 !important;
}

.node {
  border-radius: 30%;
  cursor: pointer;
  height: auto;
  padding-bottom: 6px;
  box-sizing: content-box;
  position: relative;
  user-select: none;
}

.selectpicker {
    width: 100px !important;
}

.rete {
    height: 430px;
    padding: 10px;
    border: 1px solid #bbbbbb;
    border-radius: 5px;
}

.userinput {
    width: 105px !important;
}

#id-graph-alert {
    color: red;
}

</style>

<div class="card mb-4">
    <div class="card-body">
        <form method="post" enctype="multipart/form-data" action="{% url 'workflow:signature' radicate=radicate %}" autocomplete="off">

            {% csrf_token %}

            <input id="id-graph" name="graph" type="hidden" value="">
            <input id="id-id" name="id" type="hidden" value="{{ id }}">
            <input id="id-next" name="next" type="hidden" value="{{ next }}">

            <div class="rete">

                {% if messages %}
                    {% for message in messages %}
                        <div id="id-graph-alert">{{ message|safe }}</div>
                    {% endfor %}
                {% endif %}

                <div id="rete"></div>
            </div>

            <input type="submit" name="button" class="btn btn-success mt-3" value="Guardar">
        </form>
    </div>
</div>

<div class="modal fade" id="user_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-m" role="document">
        <div class="modal-content">
            <div class="modal-header">
                Búsqueda de Usuario
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row justify-content-center">
                <div class="col-12" id="file-display-field">
                    {% include "workflow/select_user_and_time.html" %} 
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'node_modules/vue/dist/vue.min.js' %}"></script>
<script src="{% static 'node_modules/rete/build/rete.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js"></script>
<script src="{% static 'node_modules/rete-connection-plugin/build/connection-plugin.min.js' %}"></script>
<script src="{% static 'node_modules/rete-context-menu-plugin/build/context-menu-plugin.common.js' %}"></script>
<script src="{% static 'node_modules/rete-context-menu-plugin/build/context-menu-plugin.min.js' %}"></script>
<script src="{% static 'node_modules/rete-vue-render-plugin/build/vue-render-plugin.min.js' %}"></script>
<script src="{% static 'node_modules/rete-comment-plugin/build/comment-plugin.min.js' %}"></script>
<script src="{% static 'node_modules/rete-keyboard-plugin/build/keyboard-plugin.min.js' %}"></script>
<script src="{% static 'node_modules/rete-area-plugin/build/area-plugin.min.js' %}"></script>

{{ graph|json_script:"graph" }}

<script>

var graph = JSON.parse(document.getElementById('graph').textContent);
var actSocket = new Rete.Socket("Action");
var mounted = false;

function validateUser() {
    if ($.isNumeric($("#user_selected_time").val()) &&
        $("#user_selected").val() != '-1' && 
        $("#user_selected").val() != null) {
        $('#user_selected_submit').prop('disabled', false);
    } else {
        $('#user_selected_submit').prop('disabled', true);
    }
}

function getVueUserControl(key, userType, user, time, permission) {
    return {
        props: ['emitter', 'ikey', 'getData', 'putData', ],
        template: `<input id="${key}_selected" class="userinput" readonly=true v-on:click="showModal($event)" \
                :value=username data-toggle="tooltip" data-placement="top" \
                :title=title />`
        ,
        data() {
            if (!time){
                time = 2;
            }
            return {
                value: user.id,
                username: user.username,
                area_id: user.area_id,
                user: user,
                title: `[${user.username}] ${user.first_name} ${user.last_name}`,
                time: time,
                permission: permission
            }
        },
        methods: {
            showModal(e){
                permissions = [this.permission]
                $('#user_selected').find('option').remove().end();
                $("#user_selected").append('<option value=-1>[sin usurio] seleccione un usuario</option>')
                if (this.value) {
                    $("#user_selected").append(
                        `<option selected value=${this.value}>${this.title}</option>`)
                }
                $("#user_selected").selectpicker('refresh');
                $('#user_selected').selectpicker('render');
                $('#user_selected_time').val(this.time)
                $('#user_selected_submit').prop('disabled', true);
                self = this;
                $('#user_selected_submit').click(function(){ 
                    self.value = $('#user_selected').val();
                    self.area_id = $('#user_selected_area').val();
                    self.title = $('#user_selected').find("option:selected").text()
                    self.username = self.title.match(/\[(.*)\]/i)[1];
                    $('.collapse').collapse('hide')
                    $("#headerForm").text('')
                    $('#user_modal').modal('hide')
                    self.time = $('#user_selected_time').val()
                    self.update();
                });
                $('#user_selected').change(function(){ 
                    validateUser()
                });
                $('#user_selected_time').change(function(){ 
                    validateUser()
                });
                $('#user_modal').modal()
            },
            update() {
                if (this.ikey)
                    this.putData('user', {'id': this.value, 'area_id': this.area_id})
                    this.putData('time', this.time)
                this.emitter.trigger('process');
            }
        }
    }
}

class UserControl extends Rete.Control {
    constructor(emitter, key, userType, user, time, permission) {
        if ($.isEmptyObject(user)) {
            user = {
                'id': null, 
                'username': 'sin usuario', 
                'first_name': 'seleccione un usuario', 
                'last_name': ''
            }
        } 
        super(key);
        this.component = getVueUserControl(key, userType, user, time, permission);
        this.props = {emitter, ikey: 'data'};
    }
}

class InputComponent extends Rete.Component {
    constructor(){
        super("Inicio");
    }
    builder(node) {
        var out = new Rete.Output('out', "Inicio", actSocket, true);
        return node.addOutput(out);
    }
    worker(node, inputs, outputs) {
    }
}

class OutputComponent extends Rete.Component {
    constructor(){
        super("Fin");
    }
    builder(node) {
        var inp = new Rete.Input('in', "Fin", actSocket, true);
        return node.addInput(inp);
    }
    worker(node, inputs, outputs) {
    }
}

class GuarantorUserComponent extends Rete.Component {
    constructor(){
        super("Visto Bueno"); 
    }
    builder(node) {
        var ctrl = new UserControl(this.editor, node.id, 'guarantoruser', node.data.user, node.data.time, 'approbation');
        var inp = new Rete.Input('in',"Inicio", actSocket, true);
        var out = new Rete.Output('out', "Fin", actSocket, true);
        return node
            .addInput(inp)
            .addControl(ctrl)
            .addOutput(out);
    }
    worker(node, inputs, outputs) {
    }
}

class SigningUserComponent extends Rete.Component {
    constructor(){
        super("Firma Personal"); 
    }
    builder(node) {
        var ctrl = new UserControl(this.editor, node.id, 'signinguser', node.data.user, node.data.time, 'personal_signature');
        var inp = new Rete.Input('in',"Inicio", actSocket, true);
        var out = new Rete.Output('out', "Fin", actSocket, true);
        return node
            .addInput(inp)
            .addControl(ctrl)
            .addOutput(out);
    }

    worker(node, inputs, outputs) {
        var value = inputs['in'].length ? inputs['in'][0] : node.data.value;
        outputs['value'] = value;
    }
}

class LegalSigningUserComponent extends Rete.Component {
    constructor(){
        super("Firma Jurídica");
    }
    builder(node) {
        var ctrl = new UserControl(this.editor, node.id, 'legalsigninguser', node.data.user, node.data.time, 'legal_signature');
        var inp = new Rete.Input('in',"Inicio", actSocket, true);
        var out = new Rete.Output('out', "Fin", actSocket, true);
        return node
            .addInput(inp)
            .addControl(ctrl)
            .addOutput(out);
    }

    worker(node, inputs, outputs) {
        var value = inputs['in'].length ? inputs['in'][0] : node.data.value;
        outputs['value'] = value;
    }
}

var container = document.querySelector('#rete');
var components = [new GuarantorUserComponent(), new SigningUserComponent(), 
                  new LegalSigningUserComponent(), new InputComponent(), 
                  new OutputComponent()];

var editor = new Rete.NodeEditor('demo@0.1.0', container);
editor.use(ConnectionPlugin.default);
editor.use(VueRenderPlugin.default);   
editor.use(ContextMenuPlugin.default, {
    searchBar: false,
});
editor.use(AreaPlugin);
editor.use(CommentPlugin.default);
editor.use(KeyboardPlugin);

var engine = new Rete.Engine('demo@0.1.0');


components.map(c => {
    editor.register(c);
    engine.register(c);
});

editor.on('connectioncreate connectionremove nodecreate noderemove process', ()=>{
    compile();
    if (mounted) {
        $('#id-graph-alert').html('');
    }
});

async function compile() {
    await engine.abort();
    await engine.process(editor.toJSON());
    $('#id-graph').val(JSON.stringify(editor.toJSON()));
}

editor.fromJSON(graph).then(() => {
    editor.view.resize();
    compile();
    mounted = true;    
});

editor.on('zoom', (e) => {
  let k = e.transform.k; 
  if (e.zoom > k) { 
    e.zoom = k + 0.02;
  } else if (e.zoom < k) {
    e.zoom = k - 0.02;
  }
  e.zoom = +e.zoom.toFixed(2);
  return e.source !== 'dblclick'; 
});

</script>

{% endblock %}