core/urls.py
from django.conf.urls import url
from core import views
from core.services import Scheduler
from django.urls import path


app_name = 'core'

urlpatterns = [
    path('home_global.css/', views.StyleSettingsView.as_view(), name='home-global'),
    path('test-quill/<int:pk>/', views.TestViewQuill.as_view(), name='test_view'),
    path('test-tiny/<int:pk>/', views.TestViewTiny.as_view(), name='test_view'),
]

reports/urls.py
# -*- coding: utf-8 -*-
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls import url

from .api import (
    ApiVersion, Index, Info, ListCubes,
    CubeModel, CubeAggregation, CubeCell,
    CubeReport, CubeFacts, CubeFact, CubeMembers
)

from django.urls import path
from reports import views

app_name = 'reports'

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    path('version/', ApiVersion.as_view(), name="version"),
    path('info/', Info.as_view(), name="info"),
    path('cubes/', ListCubes.as_view(), name="cubes"),
    path('cube/<str:cube_name>/model/', CubeModel.as_view(), name="cube_model"),
    path('cube/<str:cube_name>/aggregate/', CubeAggregation.as_view(), name="cube_aggregation"),
    path('cube/<str:cube_name>/cell/', CubeCell.as_view(), name="cube_cell"),
    path('cube/<str:cube_name>/report/', CubeReport.as_view(), name="cube_report"),
    path('cube/<str:cube_name>/facts/', CubeFacts.as_view(), name="cube_facts"),
    path('/cube/<str:cube_name>/facts/', CubeFacts.as_view(), name="cube_facts"),
    path('cube/<str:cube_name>/fact/<str:fact_id>/', CubeFact.as_view(), name="cube_fact"),
    path('cube/<str:cube_name>/members/<str:dimension_name>/', CubeMembers.as_view(), name="cube_members"),
    path('/cube/<str:cube_name>/members/<str:dimension_name>/', CubeMembers.as_view(), name="cube_members"),
    path('dashboard/', views.cubes, name="dashboard"),
]

rino/urls.py
from django.contrib import admin
from django.urls import include,path
from correspondence import views
from pqrs import views as pqrs_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views as core_views
from django.conf.urls import url

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('correspondence/', include('correspondence.urls', namespace='correspondence')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('workflow/', include('workflow.urls', namespace='workflow')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', views.index, name='index'),
    # reset passwords urls
    path('password_reset/', core_views.password_reset_request, name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('calendar/holidays/', core_views.holidays, name='holidays'),
    path('calendar/weekends/', core_views.weekends, name='weekends'),
    path('calendar/not-working-days/', core_views.not_working_days, name='not_working_days'),
    path('signature_flow/users/', core_views.signature_flow_users, name='signature_flow_users'),
    #path('password_reset/', include('password_reset.urls', namespace='password_reset'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # to import static in deployment



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/models.py
from django.db import models
from django.utils import timezone

class Date(models.Model):
    date = models.DateField(default=timezone.now, null=False, blank=False)
    day = models.SmallIntegerField(default=1, blank=False, null=False)
    month = models.SmallIntegerField(default=1, blank=False, null=False)
    year = models.SmallIntegerField(default=1, blank=False, null=False)
    week = models.SmallIntegerField(default=1, blank=False, null=False)
    weekyear = models.SmallIntegerField(default=1, blank=False, null=False)

    class Meta:
        db_table = "dw_date"

class Subtype(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    type_id = models.IntegerField(default=1, blank=False, null=False)
    type_name = models.CharField(max_length=256, blank=False, null=False)

    class Meta:
        db_table = "dw_subtype"     

class PQRS(models.Model):
    subtype = models.ForeignKey(
        Subtype, on_delete=models.PROTECT, null=True, blank=True)    
    date = models.ForeignKey(
        Date, on_delete=models.PROTECT, null=True, blank=True)
    amount = models.BigIntegerField(default=0, blank=False, null=False)

    class Meta:
        db_table = "dw_pqrs" 

reports/views.py
from django.shortcuts import render

def cubes(request):
    return render(request, 'reports/dashboard.html')

templates/reports/cubes_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>RINO</title>

    {% block styles %}
    {% endblock %}

    <link href="{% static 'correspondence/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'pqrs/css/styles.css' %}" rel="stylesheet" />
    
    <link rel="icon" type="image/x-icon" href="{% static 'correspondence/assets/img/favicon.jpg'%}" />
    <link rel="stylesheet" href="{% url 'core:home-global' %}" type="text/css">

  </head>
  <div id="loading">
    <img id="loading-image" src="{% static 'loader/loader.gif'%}" alt="Loading..." />
  </div>
  <body class="nav-fixed">
    <div id="layoutnav">
      <div id="layoutSidenav_content">
        {% if messages %} {% for message in messages %}
        <div class="alert {{message.tags}} alert-dismissible fade show mt-2" role="alert">
          {{message|safe}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %} {% endif %}
        <main>
          <header class="page-header page-header-dark bg-gradient-primary-to-secondary pb-10">
            <div class="container">
              <div class="page-header-content pt-4">
                <div class="row align-items-center justify-content-between">
                  <div class="col-auto mt-4">
                    <h1 class="page-header-title">
                      <a href="/">
                        <img
                          class="float-left"
                          src="{% static 'correspondence/assets/img/illustrations/FullColor_TransparentBg_1280x1024_72dpi_1.png' %}"
                          style="height: 6rem"
                        />
                      </a>
                      RINO - PQRSD
                    </h1>
                  </div>
                  <div class="col-auto mt-4 ml-auto">
                    <img
                      onerror="this.remove()"
                      class="float-right"
                      src="/media/company_logo/logo.png"
                      style="height: 6rem"
                    />
                  </div>
                </div>
              </div>
            </div>
          </header>
          <!-- Main page content-->
          <div class="container mt-n10">{% block content %} {% endblock %}</div>
          
        </main>
        <footer class="footer mt-auto footer-light">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 small">Copyright &copy; RINO 2021</div>
              <div class="col-md-6 text-md-right small">
                <a href="#!">Privacy Policy</a>
                &middot;
                <a href="#!">Terms &amp; Conditions</a>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <script src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.js' %}"></script>

    <script type="text/javascript">
        $(window).on("load", function () {
            $("#loading").hide();
            $( ":button" ).addClass( "no-after" );
        });
    </script>
    {% block script %} {% endblock %}
    
  </body>

</html>

templates/reports/dashboard.html
{% extends './cubes_template.html' %}

{% load static %}
{% block styles %}

    <link rel="stylesheet" href="{% static 'node_modules/angular-ui-grid/ui-grid.css' %}" />
    <link rel="stylesheet" href="{% static 'node_modules/font-awesome/css/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'node_modules/nvd3/build/nv.d3.css' %}" />
    <link rel="stylesheet" href="{% static 'cubes/css/cubesviewer.css' %}" />
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap-submenu/dist/css/bootstrap-submenu.css' %}" /> <!-- after cubesviewer.css! -->
    <link rel="stylesheet" href="{% static 'cubes/css/cvapp.css' %}" />
    <style type="text/css" scoped>

    .ui-grid-header {
        height: 25px !important;
    }
}

</style>

{% endblock %}

{% block content %}

<div class="card mb-4">
    <div class="card-body">
        <div>
            <div style="clear: both;"></div>

            <!-- Cubes Viewer container -->
            <div id="cubesviewer">
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}

    <script src="{% static 'node_modules/bootstrap-submenu/js/bootstrap-submenu.js' %}"></script>
    <script src="{% static 'node_modules/angular/angular.js' %}"></script>
    <script src="{% static 'node_modules/angular-cookies/angular-cookies.js' %}"></script>
    <script src="{% static 'node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js' %}"></script>
    <script src="{% static 'node_modules/angular-ui-grid/ui-grid.js' %}"></script>
    <script src="{% static 'node_modules/d3/d3.js' %}"></script>
    <script src="{% static 'node_modules/nvd3/build/nv.d3.min.js' %}"></script>
    <script src="{% static 'node_modules/flotr2/flotr2.min.js' %}"></script>
    <script src="{% static 'node_modules/masonry-layout/dist/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'cubes/js/cubesviewer.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript">

// Initialize CubesViewer when document is ready
$(document).ready(function() {

    var cubesUrl = "{{ request.scheme }}://{{ request.get_host }}{% url 'reports:index' %}"
    //var cubesUrl = "http://localhost:5000";

    cubesviewerStudio.init({
        cubesUrl: cubesUrl,
        container: $('#cubesviewer').get(0),
        debug: true
    });

});

</script>

{% endblock %}