core/urls.py
from django.conf.urls import url
from core import views
from core.services import Scheduler
from django.urls import path


app_name = 'core'

urlpatterns = [
    path('home_global.css/', views.StyleSettingsView.as_view(), name='home-global'),
    path('test-quill/<int:pk>/', views.TestViewQuill.as_view(), name='test_view'),
    path('test-tiny/<int:pk>/', views.TestViewTiny.as_view(), name='test_view'),
]

correspondence/urls.py
from django.conf.urls import url
from correspondence import views
from django.urls import path

import correspondence.api_views

app_name = 'correspondence'

urlpatterns = [
    path('api/v1/radicates/', correspondence.api_views.RadicateList.as_view(), name='search_radicates'),
    path('api/v1/radicates/<str:radi_number>/', correspondence.api_views.RadicateDetail.as_view(), name='search_radicate'),
    path('api/v1/radicates/file/<str:radi_number>/', correspondence.api_views.FileDetail.as_view(), name='search_radicate_file'),
    url(r'^$', views.index, name='index'),
    path('search-names/', views.search_names, name='search_names'),
    path('users-by-area/', views.users_by_area, name='users_by_area'),
    path('return-to-last-user/<int:radicate>', views.return_to_last_user, name='return_to_last_user'),
    path('report-to-user/<int:radicate>', views.report_to_user, name='report_to_user'),
    path('delete-from-reported/<int:radicate>', views.delete_from_reported, name='delete_from_reported'),
    path('assign-user/<int:radicate>', views.assign_user, name='assign_user'),
    path('search-content/', views.search_by_content, name='search_by_content'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('radicate/create/<int:person>/', views.create_radicate, name='create_radicate'),
    path('radicate/list/', views.RadicateList.as_view(), name='list_radicate'),
    path('radicate/<int:pk>/', views.RadicateDetailView.as_view(), name="detail_radicate"),
    path('radicate_review/<int:pk>/', views.RadicateDetailReview.as_view(), name="detail_radicate_review"),
    path('radicate-detail/<str:cmis_id>/', views.detail_radicate_cmis, name="detail_radicate_cmis"),
    path('edit-radicate/<int:id>/', views.edit_radicate, name='edit_radicate'),
    path('current-user/<int:pk>/', views.CurrentUserUpdate.as_view(), name='current_user'),
    path('recordassigned/<int:pk>/', views.RecordAssignedUpdate.as_view(), name='recordassigned'),
    path('person/create/', views.PersonCreateView.as_view(), name='create_person'),
    path('update-person/<int:pk>/', views.PersonUpdateViewNew.as_view(), name='update_person'),
    path('create-person-attorny/<uuid:pqrs_type>/', views.PersonAtronyCreate.as_view(), name='create_person_attorny'),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='detail_person'),
    path('edit-person/<int:pk>/', views.PersonUpdateView.as_view(), name='edit_person'),
    path('legal-person/create/', views.LegalPersonCreateView.as_view(), name='create_legal_person'),
    path('legal-person-update/<int:pk>/', views.LegalPersonUpdateView.as_view(), name='update_legal_person'),
    path('register/', views.register, name='register'),
    path('charts/', views.charts, name='charts'),
    path('project-answer/<int:pk>/', views.project_answer, name='project_answer'),
    path('record/create/', views.RecordCreateView.as_view(), name='create_record'),
    path('record-detail/<int:pk>/', views.RecordDetailView.as_view(), name='detail_record'),
    path('record/edit/<int:pk>/', views.RecordUpdateView.as_view(), name='edit_record'),
    path('record/list/', views.RecordListView.as_view(), name='list_records'),
    path('record/process-excel-radicates/', views.ProcessExcelRadicates.as_view(), name='process_excel_radicates'),
    path('search-person/',views.search_user,name="search_person"),
    path('radicate/thumbnail/', views.get_thumbnail, name='get_thumbnail'),
    path('radicate/file/', views.get_file, name='get_file'),
    path('get-alerts/', views.get_alerts, name='get_alerts'),
    path('disable-alert/', views.disable_alert, name='disable_alert'),
    path('create-pqrs/<uuid:pqrs>/',views.create_pqr_type,name='create_pqrs'),
    path('finish-pqrs/<uuid:pqrs>/',views.finish_pqrs,name='finish_pqrs'),
    path('request-internal-info/<int:radicate>/', views.request_internal_info, name='request_internal_info'),
    path('answer-request/<int:pk>/', views.answer_request, name='answer-request'),
]

rino/urls.py
from django.contrib import admin
from django.urls import include,path
from correspondence import views
from pqrs import views as pqrs_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views as core_views
from django.conf.urls import url

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('correspondence/', include('correspondence.urls', namespace='correspondence')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('workflow/', include('workflow.urls', namespace='workflow')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', views.index, name='index'),
    # reset passwords urls
    path('password_reset/', core_views.password_reset_request, name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('calendar/holidays/', core_views.holidays, name='holidays'),
    path('calendar/weekends/', core_views.weekends, name='weekends'),
    path('calendar/not-working-days/', core_views.not_working_days, name='not_working_days'),
    path('signature_flow/users/', core_views.signature_flow_users, name='signature_flow_users'),
    #path('password_reset/', include('password_reset.urls', namespace='password_reset'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # to import static in deployment



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

correspondence/forms.py
from django.db.models.query_utils import Q
from core.services import SystemParameterHelper
from pqrs.models import PqrsContent, SubType
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, ButtonHolder, Button, Div, HTML
from django.contrib.auth.models import User
from correspondence.models import Radicate, Record, RequestInternalInfo
from core.models import DocumentTypes, FunctionalAreaUser, Person, UserProfileInfo
from core.forms import CustomFileInput
from core.utils_services import FormatHelper
from pinax.eventlog.models import log, Log
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from core.widgets import RichTextTinyWidget

from crispy_forms.bootstrap import (
    Accordion,
    AccordionGroup
)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        exclude = ('user',)


class RadicateForm(forms.ModelForm):
    document_file = forms.FileField()

    class Meta:
        model = Radicate
        fields = ['use_parent_address', 'subject', 'annexes', 'observation', 'type', 'reception_mode',
                  'office', 'doctype']
        labels = {'use_parent_address': '¿Usar la dirección de la organización?', 'subject': 'Asunto',
                  'person': 'Remitente/Destinatario',
                  'annexes': 'Anexos', 'type': 'Tipo', 'reception_mode': 'Medio de recepción',
                  'observation': 'Observaciones', 'office': 'Dependencia',
                  'doctype': 'Tipo de documento'}
        widgets = {
            'type': forms.Select(attrs={'class': 'selectpicker'}),
            'reception_mode': forms.Select(attrs={'class': 'selectpicker'}),
            'subject': forms.TextInput(),
            'annexes': forms.TextInput(),
            'office': forms.Select(attrs={'class': 'selectpicker'}),
            'doctype': forms.Select(attrs={'class': 'selectpicker', 'data-live-search': 'true', 'data-size': '7',
                                           'title': 'Seleccione..'})
        }

    def __init__(self, *args, **kwargs):
        super(RadicateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            'use_parent_address',
            Row(
                Column('type', css_class='form-group col-md-6 mb-0'),
                Column('reception_mode', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            'subject',
            'observation',
            'annexes',
            'office',
            'doctype',
            CustomFileInput('document_file'),
            Submit('submit', 'Radicar')
        )


class SearchForm(forms.Form):
    item = forms.CharField(label='Palabra clave', help_text='Datos a buscar')



class AssignToUserForm(forms.Form):
    observations = forms.CharField(label='Observaciones:', widget=forms.Textarea())
    
class RequestInternalInformatioForm(forms.Form):
    description = forms.CharField(label='DESCRIPCIÓN SOLICITUD DE INFORMACIÓN', widget=forms.Textarea())

class ReportToUserForm(forms.Form):
    observations = forms.CharField(label='Observaciones:', widget=forms.Textarea())

class DeleteFromReportedForm(forms.Form):
    observations = forms.CharField(label='Observaciones:', widget=forms.Textarea())

class ReturnToLastUserForm(forms.Form):
    observations = forms.CharField(label='Observaciones:', widget=forms.Textarea())


class SearchContentForm(forms.Form):
    term = forms.CharField(label='Búsqueda por términos clave',
                           help_text='Introduzca el termino a buscar')

class SearchUserForm(forms.Form):
    anonymous = forms.BooleanField(
        label='Solicictante Anonimo',
        widget= forms.CheckboxInput(),
        required=False)
    doc_num = forms.CharField(label='Numero de Documento' )
    document_type= forms.ModelChoiceField(
        queryset=DocumentTypes.objects.exclude(Q(id=3) | Q(id=6)),
        label='Tipo de documento'
    )
    def __init__(self, *args, **kwargs):
        super(SearchUserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('anonymous', css_class='form-group col-md-12 mb-0'),
            ),
            Row(
                Column('document_type', css_class='form-group col-md-6 mb-0'),
                Column('doc_num',
                       css_class='form-group col-md-6 mb-0'),
            ),
            Row(
                Submit('submit', 'Buscar'), css_class='d-flex justify-content-center',
            )
        )

class SearchLegalUserForm(forms.Form):
    doc_num = forms.CharField(label='Numero de Documento' )
    verification_code = forms.CharField(label='Codigo de Verificación' )
    document_type= forms.ModelChoiceField(
        queryset=DocumentTypes.objects.filter(Q(id=3) | Q(id=6)),
        label='Tipo de documento'
    )
    def __init__(self, *args, **kwargs):
        super(SearchLegalUserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('document_type', css_class='form-group col-md-4 mb-0'),
                Column('doc_num',
                       css_class='form-group col-md-4 mb-0'),
                Column('verification_code',
                       css_class='form-group col-md-4 mb-0'),
            ),
            Row(
                Submit('submit', 'Buscar'), css_class='d-flex justify-content-center',
            )
        )


class CorrespondenceRadicateForm(forms.ModelForm):
    pqrs_creation_uploaded_files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False,
                                    label="Anexos, Documentos (Múltiples archivos - Tamaño máximo = 10 MB)")

    class Meta:
        model = PqrsContent
        fields = ('subject', 'data', 'interestGroup', 'subtype')
        labels = {'subject': 'Asunto',
                  'data': 'Detalle de la solicitud',
                  'interestGroup': 'Grupo de interés'}

    def __init__(self, *args, **kwargs):
        
        super(CorrespondenceRadicateForm, self).__init__(*args, **kwargs)        
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('subtype', css_class='form-group col-md-6 mb-0'),
                Column('interestGroup', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('subject', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('data', css_class='form-group col-md-12 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column(CustomFileInput('pqrs_creation_uploaded_files'),css_class='form-group col-12 mb-0'),
                css_class='form-row'
            ),
        )

        self.helper.layout.extend([
            Div(
                Submit('submit','Siguiente',
                css_class="btn btn-primary mx-auto",
                ),css_class="d-flex"),
                ])
        self.fields['subtype'].widget = forms.HiddenInput()
        self.fields['interestGroup'].widget = forms.HiddenInput()
        
class PersonForm(forms.ModelForm):
    email_confirmation = forms.CharField(
        label='Confirmación del correo electrónico', required=True)

    def clean_email_confirmation(self):
        cd = self.cleaned_data
        if FormatHelper.get_field_value(cd, 'email_confirmation') != FormatHelper.get_field_value(cd, 'email'):
            raise forms.ValidationError(
                'El correo de validación no coincide con el correo')
        return FormatHelper.get_field_value(cd, 'email_confirmation')

    def clean(self):
        cleaned_data = super().clean()
        cleaned_address = cleaned_data.get('address')
        cleaned_email = cleaned_data.get('email')
        if cleaned_address is None and cleaned_email is None:
            raise forms.ValidationError(
                'Por favor ingrese la dirección de contacto o el correo electrónico')
        return cleaned_data

    class Meta:
        model = Person

        fields = ['document_type', 'document_number', 'name', 'email', 'city', 'address',
                  'parent', 'preferencial_population', 'conflict_victim', 'disabilities', 'ethnic_group']
        labels = {'document_type': 'Tipo de documento',
                  'document_number': 'Número de documento',
                  'name': 'Nombres', 'email': 'Correo electrónico',
                  'city': 'Ciudad / Municipio', 'address': 'Dirección de contacto',
                  'parent': 'Entidad',
                  'preferencial_population': 'Población Preferencial (Selección Múltiple)',
                  'conflict_victim': 'Población víctima del conflicto armado',
                  'disabilities': 'Población en situación de discapacidad (Selección Múltiple)',
                  'ethnic_group': 'Grupo Étnico'}

        widgets = {
            'document_type': forms.Select(attrs={'class': 'selectpicker'}),
            'city': forms.Select(attrs={'class': 'selectpicker', 'data-live-search': 'true', 'data-size': '7'}),
            'parent': forms.Select(attrs={'class': 'selectpicker', 'data-live-search': 'true', 'data-size': '7'}),

templates/correspondence/person_detail.html
{% extends 'correspondence/main_template.html' %}

{% block content %}
<div class="card mb-4">
    <div class="card-header">Persona {{ radicate.number }}</div>
    <div class="card-body">
      <p><b>Tipo de Documento:</b> {{ person.document_type }}</p>
      <p><b>Número de documento:</b> {{ person.document_number }}</p>
      <p><b>Email:</b> {{ person.email }}</p>
      <p><b>Nombre:</b> {{ person.name }}</p>
      <p><b>Ciudad:</b> {{ person.city }}</p>
      <p><b>Dirección:</b> {{ person.address }}</p>

    </div>
    <div class="card-footer">
        <a href="{% url 'correspondence:create_radicate' person=person.pk %}" class="btn btn-success lift">Radicar</a>
        <a href="{% url 'correspondence:edit_person' pk=person.pk %}" class="btn btn-primary lift">Editar</a>
    </div>
</div>
{% endblock %}

templates/correspondence/person_form.html
{% extends 'correspondence/main_template.html' %}

{% block content %}
<div class="card mb-4">
    <div class="card-header">Persona</div>
    <div class="card-body">
    <form  method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {% crispy form %}
    </form>
    </div>
</div>
{% endblock %}

templates/correspondence/radicate_currentuser_update_form.html
{% extends 'correspondence/main_template.html'   %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card mb-4">
    <div class="card-header">Asignar {{ radicate.number }}</div>
      <div class="card-body">
        <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input class="btn btn-primary" type="submit" value="Trasladar">
        </form>
      </div>
    </div>
{% endblock %}

templates/correspondence/record_list.html
{% extends 'correspondence/main_template.html' %}

{% block content %}
  <div class="card mb-4">
      <div class="card-header">Listado de expedientes</div>
      <div class="card-body">
        <div class="datatable">
          <table class="table table-bordered table-hover" id="radicateListTable" width="100%" cellspacing='0'>
            <thead>
              <tr>
                <th>Nombre</th>
                <th class="d-none d-md-table-cell">Tipificacion</th>
                <th>Asunto</th>
                <th class="d-none d-md-table-cell">Fuente</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Nombre</th>
                <th class="d-none d-md-table-cell">Tipificacion</th>
                <th>Asunto</th>
                <th class="d-none d-md-table-cell">Fuente</th>
                <th>Acciones</th>
              </tr>
            </tfoot>
            <tbody>
              {% for record in records %}
              <tr>
                <td>{{ record.name }}</td>
                <td class="d-none d-md-table-cell">{{ record.retention }}</td>
                <td>{{ record.subject }}</td>
                <td class="d-none d-md-table-cell">{{ record.source }}</td>
                <td>
                    <a href="{% url 'correspondence:detail_record' pk=record.pk %}" class="btn btn-datatable btn-icon btn-transparent-dark"><i data-feather="eye"></i></a>
                    <a href="{% url 'correspondence:edit_record' pk=record.pk %}" class="btn btn-datatable btn-icon btn-transparent-dark"><i data-feather="edit"></i></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <a href="{% url 'correspondence:create_record' %}" class="btn btn-large btn-success">Crear Nuevo</a>
        </div>
      </div>
  </div>
{% endblock %}

templates/correspondence/template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
     integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
     crossorigin="anonymous">
     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
     <link rel="stylesheet" href="{% url 'core:home-global' %}" type="text/css">
  </head>
  <body>

    <!-- DOCUMENTATION NAVBAR -->

    <nav class="navbar  navbar-expand-lg navbar-dark bg-dark ">
      <a class="navbar-brand" href="#">
        <svg class="bi bi-box" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
        </svg> RINO
      </a>

      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- This is the actual code that creates the "hamburger icon" -->
      <!-- The data-target grabs ids to put into the icon -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-nav">

          <!-- the span class "sr-only" tells screen readers that Home is the active link, for accessibility -->
          <a class="nav-item nav-link active" href="#">Plantillas <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="#">Ayuda</a>
          <a class="nav-item nav-link" href="#">Información</a>

          <!-- DROPDOWN MENU -->
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbar-dropdown-menu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Reportes
            </a>
            <div class="dropdown-menu" aria-labelledby="navbar-dropdown-menu">
              <a class="dropdown-item" href="#">
                <svg class="bi bi-reply-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M9.079 11.9l4.568-3.281a.719.719 0 0 0 0-1.238L9.079 4.1A.716.716 0 0 0 8 4.719V6c-1.5 0-6 0-7 8 2.5-4.5 7-4 7-4v1.281c0 .56.606.898 1.079.62z"/>
                </svg>
                Trasladar
              </a>
              <a class="dropdown-item" href="http://www.google.com">
                <svg class="bi bi-info-circle-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM8 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                </svg>
                Infomar
              </a>
              <a class="dropdown-item" href="#">
                <svg class="bi bi-box-arrow-in-down" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M4.646 8.146a.5.5 0 0 1 .708 0L8 10.793l2.646-2.647a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 0 1 0-.708z"/>
                  <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-1 0v-9A.5.5 0 0 1 8 1z"/>
                  <path fill-rule="evenodd" d="M1.5 13.5A1.5 1.5 0 0 0 3 15h10a1.5 1.5 0 0 0 1.5-1.5v-8A1.5 1.5 0 0 0 13 4h-1.5a.5.5 0 0 0 0 1H13a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5v-8A.5.5 0 0 1 3 5h1.5a.5.5 0 0 0 0-1H3a1.5 1.5 0 0 0-1.5 1.5v8z"/>
                </svg>
                Descargar
              </a>

              <!-- Use this to separate a new link: -->
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">
                <svg class="bi bi-x-circle-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.146-3.146a.5.5 0 0 0-.708-.708L8 7.293 4.854 4.146a.5.5 0 1 0-.708.708L7.293 8l-3.147 3.146a.5.5 0 0 0 .708.708L8 8.707l3.146 3.147a.5.5 0 0 0 .708-.708L8.707 8l3.147-3.146z"/>
                </svg>
                Salir
              </a>
            </div>
          </div>

          <!-- SEARCH BAR -->

          </div

        </div> <!-- /.navbar-nav, left-hand content -->

        <!-- STUFF ON THE RIGHT -->
        <div class="navbar-nav ml-auto">
          <form class="form-inline my-2 my-lg-0">
            <div class="input-group">
              <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar">
              <button class="btn btn-primary" type="submit">Buscar</button>
          </div>
          </form>
        </div> <!-- /.navbar-nav, right-hand content -->

      </div> <!-- /.navbar-collapse -->
    </nav>

    <div class="alert alert-dark">
        <h1>
          <svg class="bi bi-file-earmark-arrow-down" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M4 1h5v1H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V6h1v7a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2z"/>
            <path d="M9 4.5V1l5 5h-3.5A1.5 1.5 0 0 1 9 4.5z"/>
            <path fill-rule="evenodd" d="M5.646 9.146a.5.5 0 0 1 .708 0L8 10.793l1.646-1.647a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 0-.708z"/>
            <path fill-rule="evenodd" d="M8 6a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0v-4A.5.5 0 0 1 8 6z"/>
          </svg>
          Radicación
      </h1>
    </div>

    <div class="container" role="main">
      {% block principal %}
      {% endblock %}
    </div>
  </body>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous">
  </script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script type="text/javascript">
    $(function() {
    $( "#id_item" ).autocomplete({
      source: "{% url 'correspondence:autocomplete' %}",
    });
  } );
  </script>
</html>