core/urls.py
from django.conf.urls import url
from core import views
from core.services import Scheduler
from django.urls import path


app_name = 'core'

urlpatterns = [
    path('home_global.css/', views.StyleSettingsView.as_view(), name='home-global'),
    path('test-quill/<int:pk>/', views.TestViewQuill.as_view(), name='test_view'),
    path('test-tiny/<int:pk>/', views.TestViewTiny.as_view(), name='test_view'),
]

pqrs/urls.py
from django.conf.urls import url
from pqrs import views, views_persons, views_statistics
from django.urls import path

app_name = 'pqrs'

urlpatterns = [
    path('', views.index, name='index'),
    path('pqrs-create/<uuid:pqrs>/', views.create_pqr_multiple, name='pqrs_create_multiple_person'),
    path('pqrs-detail/<int:pk>/', views.PqrDetailView.as_view(), name="pqrs_detail"),
    path('pqrs-finish-creation/<int:pk>/', views.PqrFinishCreation.as_view(), name="pqrs_finish_creation"),
    path('pqrs-type/<int:applicanType>/', views.PQRSType, name='pqrs_type'),
    path('search-person/<int:pqrs_type>/<int:person_type>/', views.search_person, name='search_person'),
    path('person-type/<int:pqrs_type>/<int:applicanType>/', views.person_type, name='person_type'),
    path('send-email-person/<int:pk>/<int:pqrs_type>/', views.send_email_person, name='send_email_person'),
    path('validate-email-person/<str:uuid_redis>/', views.validate_email_person, name='validate_email_person'),
    path('select/', views.select, name='select'),
    path('create-person/<str:pqrs_type>/', views_persons.PersonCreateView.as_view(), name='create_person'),
    path('create-legal-person/<str:pqrs_type>/', views_persons.LegalPersonCreateView.as_view(), name='create_legal_person'),
    path('create-person-attorny/<uuid:pqrs_type>/', views_persons.PersonAtronyCreate.as_view(), name='create_person_attorny'),
    path('create-person-request/<uuid:pqrs_type>/', views_persons.PersonRequestCreateView.as_view(), name='create_person_request'),
    path('edit-person/<uuid:pqrs_type>/<int:pk>/', views_persons.PersonUpdateViewNew.as_view(), name='edit_person'),
    path('edit-person-request/<uuid:pqrs_type>/<int:pk>/', views_persons.PersonUpdateViewNewRequest.as_view(), name='edit_person_request'),
    path('multi-request/<uuid:person>/', views.multi_create_request, name='multi_request'),
    path('delete-person/<uuid:pqrs_type>/<int:id>/',views.dete_person_request, name='delete_person_request'),
    path('radicate/inbox/', views.RadicateInbox.as_view(), name='radicate_inbox'),
    path('radicate/my-inbox/', views.RadicateMyInbox.as_view(), name='radicate_my_inbox'),
    path('radicate/my-reported/', views.RadicateMyReported.as_view(), name='radicate_my_reported'),
    path('radicate/email-inbox/', views.RadicateEmailInbox.as_view(), name='radicate_email_inbox'),
    path('radicate/<int:pk>/', views.PqrDetailProcessView.as_view(), name="detail_pqr"),
    path('radicate-assign/<int:pk>/', views.PqrDetailAssignView.as_view(), name="asign_detail_pqr"),
    path('radicate-email/<int:pk>/', views.PqrDetailEmailView.as_view(), name="email_detail_pqr"),
    path('radicate-reported/<int:pk>/', views.PqrDetailReportedView.as_view(), name="reported_detail_pqr"),
    path('radicate-detail/<int:pk>/', views.AssociatedRadicateDetailView.as_view(), name='associated_radicate_detail'),
    path('conclusion/', views.procedure_conclusion, name='conclusion'),
    path('consultant/', views.pqrsConsultan, name="pqrs_consultant"),
    path('consultation/result/<int:pk>/', views.PqrsConsultationResult.as_view(), name="consultation_result"),
    path('extend-request/<int:pk>', views.pqrs_extend_request, name="extend_request"),
    path('radicate-associate/<int:pk>/', views.pqrs_associate_request, name="associate_detail_pqr"),
    path('answer-request/<int:pk>', views.pqrs_answer_request, name="answer_request"),
    path('answer-request-email/<str:uuid_redis>', views.pqrs_answer_request_email, name="answer_request_email"),
    path('answer/<int:pk>/<int:actualPk>', views.pqrs_answer, name='answer'),
    path('answer-preview/<int:pk>', views.pqrs_answer_preview, name='answer_preview'),
    path('validate-captcha/<uuid:pqrs>/', views.validate_captcha, name='validate-captcha'),
    path('consultation/zip/<int:pk>', views.get_consultation_zip, name="consultation_zip"),
    path('change-classification/<int:pk>', views.change_classification, name="change_clasification"),
    path('bring-subtype/', views.bring_subtype, name="bring_subtype"),
    path('pqrs-consultant/', views.search_pqrsd, name='consultant_view'),
    path('statistics/', views_statistics.PqrsStatistics.as_view(), name='statistics'),
    path('horizontal-bar-chart/', views_statistics.calculate_horizontal_bar_chart, name="horizontal-bar-chart"),
    path('person-type-chart/', views_statistics.calculate_person_type_chart, name='person-type-chart'),
    path('state-chart/', views_statistics.calculate_state_chart, name='state-chart'),
    path('channel-chart/', views_statistics.calculate_channel_chart, name='channel-chart'),
    path('ethnic-group-chart/', views_statistics.calculate_ethnic_group_chart, name="ethnic-group-chart"),
    path('disability-condition-chart/', views_statistics.calculate_disability_condition_chart, name='disability-condition-chart'),
    path('conflict-victim-chart/', views_statistics.calculate_conflict_victim_chart, name='conflict-victim-chart'),
    path('preferential-population-chart/', views_statistics.calculate_preferential_population_chart, name='preferential-population-chart'),
    path('gender-chart', views_statistics.calculate_gender_chart, name='gender-chart'),
    path('ontime-chart', views_statistics.calculate_ontime_chart, name='ontime-chart'),
    path('calculate-statistics/', views_statistics.calculate_statistics, name='calculate-statistics'),
    path('records-form/', views.records_form, name='records_form'),
    path('records-form-param/<int:pk>/', views.records_form_param, name='records_form_parameter'),
    path('records-detail/<int:pk>/', views.RecordDetailView.as_view(), name='records_detail'),
    path('records-list/', views.RecordListView.as_view(), name='records_list'),
    path('create-room/', views.create_room, name='create_room'),
]

rino/urls.py
from django.contrib import admin
from django.urls import include,path
from correspondence import views
from pqrs import views as pqrs_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core import views as core_views
from django.conf.urls import url

urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('correspondence/', include('correspondence.urls', namespace='correspondence')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('workflow/', include('workflow.urls', namespace='workflow')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('', views.index, name='index'),
    # reset passwords urls
    path('password_reset/', core_views.password_reset_request, name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('calendar/holidays/', core_views.holidays, name='holidays'),
    path('calendar/weekends/', core_views.weekends, name='weekends'),
    path('calendar/not-working-days/', core_views.not_working_days, name='not_working_days'),
    path('signature_flow/users/', core_views.signature_flow_users, name='signature_flow_users'),
    #path('password_reset/', include('password_reset.urls', namespace='password_reset'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # to import static in deployment



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pqrs/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.db.models import CheckConstraint, Q, F
from django.utils import tree
from django.contrib.postgres.fields import ArrayField
from core.models import RequestResponse, BaseModel, Person,PersonRequest,Alerts
from correspondence.models import Radicate
from crum import get_current_user
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
import uuid

class InterestGroup(BaseModel):
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=128, null=False)
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(InterestGroup, self).save()
    def __str__(self):
        return self.name

    class Meta:
        verbose_name= 'Grupo de interes PQRSD'
        verbose_name_plural= 'Grupos de interes PQRSD'

class Type(models.Model):
    name = models.CharField(max_length=128,editable=False)
    description = models.CharField(blank=False, null=False, max_length=256,default='')
    asociated_icon = models.CharField(blank=False, null=False, max_length=50,default='')
    max_response_days = models.SmallIntegerField(blank=False, null=False, default=15)
    min_response_days = models.SmallIntegerField(blank=False, null=False, default=1)
    is_selectable = models.BooleanField(default=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name= 'Tipo PQRSD'
        verbose_name_plural= 'Tipos PQRSD'

class SubType(models.Model):
    type = models.ForeignKey(Type, on_delete=models.PROTECT, related_name='subtypes')
    description = models.CharField(blank=False, null=False, max_length=256,default='')
    name = models.CharField(max_length=128)
    max_response_days = models.SmallIntegerField(blank=False, null=False, default=15)
    min_response_days = models.SmallIntegerField(blank=False, null=False, default=1)
    alerts = models.ManyToManyField(Alerts, related_name="alerts_subtype",blank=True)
    def __str__(self):
        return self.type.name + ' / ' + self.name
    
    def save(self, *args, **kwargs):
        if(self.max_response_days <= self.type.max_response_days):
            super(SubType, self).save(*args, **kwargs)
        else:
            raise Exception("max_response_days should be lower or equal to type.max_response_days")
    class Meta:
        verbose_name= 'Sub tipo PQRSD'
        verbose_name_plural= 'Sub tipos PQRSD'
class PQRS(models.Model):
        
    uuid = models.UUIDField(editable=False, default=uuid.uuid4, unique=True)
    pqr_type = models.ForeignKey(Type,on_delete=models.PROTECT,related_name='pqrs_object_type',null =True)
    principal_person = models.ForeignKey(Person, on_delete=models.PROTECT,related_name='pqrs_object_principal_person',null=True)
    multi_request_person = models.ManyToManyField(PersonRequest, related_name="multi_pqrs_request_person")

    class Meta:
        verbose_name= 'Objeto PQRSD'
        verbose_name_plural= 'Objetos PQRSD'
# Create your models here.
class PqrsContent(Radicate):
    response_mode = models.ForeignKey(RequestResponse, on_delete=models.PROTECT, related_name='pqrs_response_mode')
    interestGroup = models.ForeignKey(InterestGroup, on_delete=models.PROTECT, related_name='pqr_interest_group', null=True, blank= True)
    subtype = models.ForeignKey(SubType, on_delete=models.PROTECT, related_name='pqr_type', null=True)
    pqrsobject = models.ForeignKey(PQRS,related_name='pqr_type_object', on_delete=models.PROTECT,blank=True, null=True)
    agreement_personal_data = models.BooleanField()

    def get_absolute_url(self):
        return reverse('pqrs_detail', args=[self.id])

    def get_pqrs_type_subtype(self):
        return f"{self.pqrsobject.pqr_type.name if self.pqrsobject and self.pqrsobject.pqr_type  else ''} {self.subtype.name if self.subtype else ''}"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # user = get_current_user()
        # if user is not None:
        #     if not self.pk:
        #         self.user_creation = user
        #     else:
        #         self.user_updated = user
        super(PqrsContent, self).save()
    class Meta:
        verbose_name= 'Contenido PQRSD'
        verbose_name_plural= 'Contenidos PQRSD'

class Record(BaseModel):
    class Phases(models.TextChoices):
        GESTION = 'AG', _('Archivo de Gestión')
        CREATED = 'AC', _('Archivo Central')
        ASSIGNED = 'AI', _('Archivo Inactivo')
    class SecurityLevels(models.TextChoices):
        PUBLIC = 'PU', _('Público')
        PRIVATE = 'PR', _('Privado')
        DEPENDENCE = 'DE', _('Dependencia')
        USER = 'US', _('Usuario')

    name = models.TextField(max_length=30, null=False, db_index=True, default='Por asignar')
    type = models.ForeignKey(Type,on_delete=models.PROTECT,null=False)
    subtype = models.ForeignKey(SubType,on_delete=models.PROTECT,null=False)
    initial_date = models.DateField(null=False, default=datetime.now)
    responsable = models.ForeignKey(User, on_delete=models.PROTECT, default=False)
    status = models.CharField(max_length=2, choices=Phases.choices, default=Phases.GESTION)
    subject = models.CharField(max_length=256, null=True)
    source = models.CharField(max_length=256, null=True)
    observations = models.CharField(max_length=256, null=True)
    security_levels = models.CharField(max_length=2, choices=SecurityLevels.choices, default=SecurityLevels.PUBLIC)
    cmis_id = models.TextField(max_length=128, null=False, default='Por asignar')

    radicates = models.ManyToManyField(Radicate, related_name='records', blank=True)

templates/pqrs/answer_form.html
{% extends 'correspondence/main_template.html' %}
{% load crispy_forms_tags %}
<!-- BLOCK Content -->
{% block content %}
<div class="card mb-4">
    <div class="card-body">
        <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="form-group offset-5 col-md-4 my-5">
                {{ form.number|as_crispy_field }}
            </div>
            <div class="card mb-4">
                <div class="card-header">
                    Datos destinatario
                </div>
                <div class="card-body">
                    <div class="container"> 
                        {% crispy form %}
                        <div class="form-row">
                            <div class="form-group offset-3 col-md-3 mb-0">
                                <button type="submit" class="btn btn-primary w-75">Responder PQRSD</button>
                            </div>
                            <div class="form-group col-md-3 mb-0">
                                <a class="btn btn-primary w-75" href="{% url 'pqrs:detail_pqr' pk=radicate.id %}">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="answerModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center">
          <div class="col-12" id="file-display-field">
            <embed class="w-100" height="900" src="{}"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %} 
    $("#id_answer_uploaded_files").fileinput({
        theme: 'fas',
        allowedFileExtensions: ['PDF', 'DOC', 'DOCX', 'XLS', 'XLSX', 'EXCEL', 'PPT', 'PPTX', 
                                'JPG', 'GIF', 'PNG', 'TIFF', 'BMP', 'WAV', 'MP3', 'AVI', 'MPEG', 
                                'MPG', 'OGG', 'M4A', 'MP4', 'WMV', 'OGV'],
        overwriteInitial: false,
        maxFileSize:10000,
        language: 'es',
        showUpload: false,
        showCancel: false,
        previewFileIconSettings: {
            'docx': '<i class="fas fa-file-word text-primary mt-4"></i>',
            'xlsx': '<i class="fas fa-file-excel mt-4" style="color:green;"></i>'
        },
        slugCallback: function (filename) {
            return filename.replace('(', '_').replace(']', '_');
        }
    });

    $('#id_edit_subject').change(function(){
      if(this.checked){
        $("#id_subject").attr("readonly", false);
      }
      else{
        $("#id_subject").attr("readonly", true);
      }
    });

{% endblock %}

templates/pqrs/consultation_result.html
{% extends 'pqrs/template.html' %}
{% load pqrs_extras %}

{% block content %} 
    <div class="card mb-4">
        <div class="card-header">
            Resultado
        </div>
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="row">
                            <input class="short" type="text" readonly value={{ pqrs.number }}
                            style="border: 1px solid;
                                   background: #FAFAFA;
                                   border-radius: 7px;
                                   text-align: center;
                                   height:50px;
                                   width:200px;
                                   font-size:20px;
                                   font-weight: bold">
                        </div>
                        <div class="row mt-4">
                            <div class="col-8">
                                <b>Fecha de radicación:</b>
                            </div>
                            <div class="col-4">
                                {{ pqrs.date_radicated|simple_date }}
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-8">
                                <b>Fecha Máxima de respuesta:</b>
                            </div>
                            <div class="col-4">
                                {{ pqrs.date_radicated|max_response_date:pqrs.subtype.max_response_days }}
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-8">
                                <b>Estado:</b>
                            </div>
                            <div class="col-4">
                               {{ pqrs.get_status_str }}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="row mt-4">
                            <h1><b>Respuesta</b></h1>
                        </div>
                        <div class="row">
                            <table class="table table-bordered">
                                <thead>
                                    <tr class="text-center">
                                        <th scope="col">Radicado</th>
                                        <th scope="col">Fecha</th>
                                        <th scope="col">Descargar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for answer in answers %}
                                    <tr>
                                        <td class="text-center">{{ answer.number }}</td>
                                        <td class="text-center">{{ answer.date_radicated|simple_date }}</td>
                                        <td class="text-center"><a href='{% url "pqrs:consultation_zip" pk=answer.id %}')>{{ answer }}.zip</a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                    
                            </table>
                        </div>
                    </div>
                </div>
                <br><br><br>
            </div>
        </div>
    </div>
{% endblock %}

templates/pqrs/person_type.html
{% extends 'pqrs/template.html' %} {% load static %}
<!-- BLOCK Content -->
{% block content %}
<div class="row">
  <div class="col-xl-12 mb-12">
    <div class="card">
      <div class="card-body">
        <div class="row no-gutters">
          <div class="col-md-2">
            <img class="img-fluid" src="{% static 'correspondence/assets/img/illustrations/browser-stats.svg' %}" alt="..."
              style="width: 8rem" />
          </div>
          <div class="col-md-8">
            <div class="card-body py-5">
              <h1 class="card-title text-primary text-center">RINO PQRSD</h1>
            </div>
          </div>
        </div>
        {% if person_type %}
        <div class="row">
          <div class="col-xxl-12 col-xl-12 col-md-12 my-4">
            <h2 class="text-center mx-auto mb-2">Tipo Persona</h2>
            <h3 class="text-center mx-auto mb-2">{{person_type_message}}</h3>
          </div>
          {% for personType in person_type %}
          <div class="col-xxl-6 col-xl-6 col-md-6 my-4">
            <div class="card">
              <div class="card-body">
                <a
                  class="btn col-12 d-flex"
                  href="{% url 'pqrs:search_person' pqrs_type=pqrs_type person_type=personType.id %}"
                >
                  <h2 class="text-center m-auto">{{personType.name}}</h2>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% else %}
        <h1>Upss Algo Paso</h1>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/pqrs/radicate_email_inbox.html
{% extends 'pqrs/template_radicate_inbox.html' %} {% load static %} {% block actions %}
    <a href="{% url 'pqrs:email_detail_pqr' pk=pqrs.pk  %}" role="button">
        <i class="fas fa-plus-circle fa-2x" style="color: #0000ff;"></i>
    </a>
{% endblock %}

templates/pqrs/radicate_inbox.html
{% extends 'pqrs/template_radicate_inbox.html' %} {% load static %} {% block actions %}
    <a href="{% url 'pqrs:asign_detail_pqr' pk=pqrs.pk  %}" role="button">
        <i class="fas fa-plus-circle fa-2x" style="color: #0000ff;"></i>
    </a>
{% endblock %}

templates/pqrs/radicate_my_inbox.html
{% extends 'pqrs/template_radicate_inbox.html' %} {% load static %} {% block actions %}
    <a href="{% url 'pqrs:detail_pqr' pk=pqrs.pk  %}" role="button">
        <i class="fas fa-plus-circle fa-2x" style="color: #0000ff;"></i>
    </a>
{% endblock %}

templates/pqrs/radicate_reported_inbox.html
{% extends 'pqrs/template_radicate_inbox.html' %} {% load static %} {% block actions %}
    <a href="{% url 'pqrs:reported_detail_pqr' pk=pqrs.pk  %}" role="button">
        <i class="fas fa-plus-circle fa-2x" style="color: #0000ff;"></i>
    </a>
{% endblock %}

templates/pqrs/record_detail.html
{% extends 'correspondence/main_template.html' %}

{% block content %}
<div class="card mb-4">
    <div class="card-header">Expediente {{ record.id }}</div>
    <div class="card-body">
        <div class="card-header">Aplicaci&oacute;n de la TRD del Expediente</div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p class="text-dark">
                        <p class="text-primary">
                        Serie
                        </p>
                        <i data-feather="archive"></i>
                        {{record.type.name}}
                    </p>
                </div>
                <div class="col-md-6">
                    <p class="text-dark">
                        <p class="text-primary">
                        Sub-Serie
                        </p>
                        <i data-feather="archive"></i>
                        {{record.subtype.name}}
                    </p>
                </div>
            </div>
        </div>
         <div class="card-header">Informaci&oacute;n del Expediente</div>
        <div class="card-body">
            <div class="row ">
                <div class="col-md-6 mb-2">
                    <p class="text-primary">
                    Nombre
                    </p>
                    <i data-feather="bookmark"></i>
                    {{record.name}}
                </div>
                <div class="col-md-6 mb-2">
                    <p class="text-primary">
                    Responsable
                    </p>
                    <i data-feather="user"></i>
                    {{record.responsable}}
                </div>
                <div class="col-md-4 mb-2">
                        <p class="text-primary">
                        Fecha inicial
                        </p>
                        <i data-feather="calendar"></i>
                        {{record.initial_date}}
                </div>
                <div class="col-md-4 mb-2">
                        <p class="text-primary">
                        Asunto
                        </p>
                        <i data-feather="align-justify"></i>
                        {{record.subject}}
                </div>
                <div class="col-md-4 mb-2">
                        <p class="text-primary">
                        Fuente
                        </p>
                        <i data-feather="book-open"></i>
                        {{record.source}}
                </div>
                <div class="col-md-12 mb-2">
                    <p class="text-primary">
                    Observaciones
                    </p>
                    <i data-feather="clipboard"></i>
                    {{record.observations}}
                </div>
                <div class="col-md-6 mb-2">
                    <p class="text-primary">
                    Estado
                    </p>
                    <i data-feather="compass"></i>
                    {{record.get_status_display}}
                </div>
                <div class="col-md-6 mb-2">
                    <p class="text-primary">
                    Seguridad
                    </p>
                    <i data-feather="codepen"></i>
                    {{record.get_security_levels_display}}
                </div>
            </div>
        </div>
        <div class="d-flex ">
            <button class="btn btn-success mx-auto">Regresar</button>
        </div>
    </div>

</div>
{% endblock %}

templates/pqrs/search_person_answer_form.html
{%  extends 'pqrs/template.html'  %}
{% block content %}
{% load crispy_forms_tags %}


<div class="card mb-4">
    <div class="card-header">Búsqueda de Solicitante</div>
    <div class="card-body">
      <div class="alert alert-success mt-4" role="alert">
        <h4 class="alert-heading">Remitentes</h4>
          <p>{{ msg }}</p>
        <hr>
      </div>
    </div>
</div>
{% endblock %}

templates/pqrs/search_person_form.html
{% extends 'pqrs/template.html' %} {% block content %} 

<div class="card mb-4">
  <div class="card-header">Búsqueda de Solicitante</div>
  <div class="card-body">
    <form action="{% url 'pqrs:search_person' pqrs_type=pqrs_type person_type=person_type%}" method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {% crispy form %}
    </form>
    <div class="alert alert-success mt-4" role="alert">
      <h4 class="alert-heading">Remitentes</h4>
      <p>
        Debes realizar una búsqueda de remitentes antes de la entrada de documentos, puedes realizarla con nombres
        personales, direcciones, correo electrónico o nombre de la organización
      </p>
      <hr />
      <p class="mb-0">Una vez encontrado el remitente puedes seguir con los pasos</p>
    </div>
  </div>
</div>
{% if list %}
<div class="card mb-4">
  <div class="card-header">Resultado</div>
  <div class="card-body">
    <div class="row">
      {% for person in list%}
      <div class="col-md-4">
        <div class="card border-primary mb-3">
          <h5 class="card-header text-primary">
            Resultado {{forloop.counter}}
            <a
              title="Enviar correo"
              data-toggle="tooltip"
              href="{% url 'pqrs:send_email_person' pk=person.pk pqrs_type=pqrs_type %}"
              class="btn btn-datatable btn-icon btn-transparent-dark"
            >
              <i style="height: 1.5rem; width: 1.5rem" data-feather="mail"></i>
            </a>
          </h5>
          <div class="card-body border-primary">
            {% if person_type == 1 %}
            <p class="card-text">Nombre: {{ person.get_full_name }}</p>
            <p class="card-text">Correo: {{ person.get_anonymized_email }}</p>
            <p class="card-text">Dirreci&oacute;n: {{person.get_anonymized_address }}</p>
            {% else %}
            <p class="card-text">Razon social: {{ person.company_name }}</p>
            <p class="card-text">Correo: {{ person.get_anonymized_email }}</p>
            <p class="card-text">Representante: {{person.get_anonymized_representative }}</p>
            {% endif %}
            
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% else %} {% if person_form %}
<div class="card mb-4">
  <div class="card-header">Persona</div>
  <div class="card-body">
    <form method="post" id="sender_create_form" 
    {% if person_type == 1 %}
    action="{% url 'pqrs:create_person' pqrs_type=pqrs_type %}"
    {% else %}
    action="{% url 'pqrs:create_legal_person' pqrs_type=pqrs_type %}"
    {% endif %}>
      {% crispy person_form %} {% csrf_token %}
    </form>
  </div>
</div>

{% endif %} {% endif %} {% endblock %}
{% block script %} 
function disableBack() { window.history.forward(); }
        setTimeout("disableBack()", 0);
        window.onunload = function () { null };
{% endblock %}